# Production Environment Values for AI Market Terminal Helm Chart

global:
  environment: production
  imageRegistry: your-registry
  imageTag: "0.9.0-beta"

api:
  replicaCount: 5
  image:
    repository: ai-market-api
    tag: "0.9.0-beta"
    pullPolicy: IfNotPresent
  
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  
  env:
    - name: DATABASE_URL
      value: "postgresql://ai_market_user:$(POSTGRES_PASSWORD)@postgres-service:5432/ai_market_terminal"
    - name: REDIS_URL
      value: "redis://redis-service:6379/0"
    - name: JWT_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: production-secrets
          key: jwt-secret-key
    - name: STRIPE_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: production-secrets
          key: stripe-secret-key
    - name: STRIPE_WEBHOOK_SECRET
      valueFrom:
        secretKeyRef:
          name: production-secrets
          key: stripe-webhook-secret
    - name: POSTHOG_API_KEY
      valueFrom:
        secretKeyRef:
          name: production-secrets
          key: posthog-api-key
    - name: OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: production-secrets
          key: openai-api-key
    - name: OAUTH_GOOGLE_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: production-secrets
          key: oauth-google-client-id
    - name: OAUTH_GOOGLE_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: production-secrets
          key: oauth-google-client-secret
    - name: OAUTH_GITHUB_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: production-secrets
          key: oauth-github-client-id
    - name: OAUTH_GITHUB_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: production-secrets
          key: oauth-github-client-secret
    - name: ENVIRONMENT
      value: "production"
    - name: LOG_LEVEL
      value: "INFO"
    - name: DEBUG
      value: "false"
    - name: BETA_INVITE_LIMIT
      value: "200"

web:
  replicaCount: 5
  image:
    repository: ai-market-web
    tag: "0.9.0-beta"
    pullPolicy: IfNotPresent
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "400m"
  
  env:
    - name: REACT_APP_API_URL
      value: "https://api.aimarketterminal.com"
    - name: REACT_APP_POSTHOG_KEY
      valueFrom:
        secretKeyRef:
          name: production-secrets
          key: posthog-api-key
    - name: REACT_APP_STRIPE_PUBLISHABLE_KEY
      valueFrom:
        secretKeyRef:
          name: production-secrets
          key: stripe-publishable-key
    - name: REACT_APP_ENVIRONMENT
      value: "production"
    - name: REACT_APP_BETA_MODE
      value: "true"

postgres:
  enabled: true
  image:
    repository: postgres
    tag: "15-alpine"
  
  auth:
    postgresPassword: "production_secure_password_2024"
    database: "ai_market_terminal"
    username: "ai_market_user"
  
  primary:
    persistence:
      enabled: true
      size: 100Gi
      storageClass: "ssd"
  
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"

redis:
  enabled: true
  image:
    repository: redis
    tag: "7-alpine"
  
  auth:
    enabled: false
  
  master:
    persistence:
      enabled: true
      size: 20Gi
      storageClass: "ssd"
  
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/hsts: "true"
    nginx.ingress.kubernetes.io/hsts-max-age: "31536000"
    nginx.ingress.kubernetes.io/hsts-include-subdomains: "true"
    nginx.ingress.kubernetes.io/hsts-preload: "true"
  
  hosts:
    - host: aimarketterminal.com
      paths:
        - path: /
          pathType: Prefix
          service:
            name: web-service
            port: 80
    - host: api.aimarketterminal.com
      paths:
        - path: /
          pathType: Prefix
          service:
            name: api-service
            port: 8000
    - host: beta.aimarketterminal.com
      paths:
        - path: /
          pathType: Prefix
          service:
            name: web-service
            port: 80
  
  tls:
    - secretName: production-tls
      hosts:
        - aimarketterminal.com
        - api.aimarketterminal.com
        - beta.aimarketterminal.com

monitoring:
  prometheus:
    enabled: true
    retention: "30d"
  
  grafana:
    enabled: true
    adminPassword: "production_admin_2024"
    persistence:
      enabled: true
      size: 20Gi

secrets:
  enabled: true
  existingSecret: "production-secrets"

config:
  enabled: true
  existingConfigMap: "production-config"

# Production-specific configurations
production:
  beta:
    enabled: true
    inviteLimit: 200
    waitlistEnabled: true
    referralTracking: true
  
  analytics:
    posthogEnabled: true
    conversionTracking: true
    funnelAnalysis: true
  
  support:
    githubIssuesEnabled: true
    slackIntegration: true
    emailSupport: true
