# Staging Environment Values for AI Market Terminal Helm Chart

global:
  environment: staging
  imageRegistry: your-registry
  imageTag: "0.9.0-beta"

api:
  replicaCount: 3
  image:
    repository: ai-market-api
    tag: "0.9.0-beta"
    pullPolicy: IfNotPresent
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  
  env:
    - name: DATABASE_URL
      value: "postgresql://ai_market_user:$(POSTGRES_PASSWORD)@postgres-service:5432/ai_market_terminal"
    - name: REDIS_URL
      value: "redis://redis-service:6379/0"
    - name: JWT_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: staging-secrets
          key: jwt-secret-key
    - name: STRIPE_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: staging-secrets
          key: stripe-secret-key
    - name: STRIPE_WEBHOOK_SECRET
      valueFrom:
        secretKeyRef:
          name: staging-secrets
          key: stripe-webhook-secret
    - name: POSTHOG_API_KEY
      valueFrom:
        secretKeyRef:
          name: staging-secrets
          key: posthog-api-key
    - name: OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: staging-secrets
          key: openai-api-key
    - name: OAUTH_GOOGLE_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: staging-secrets
          key: oauth-google-client-id
    - name: OAUTH_GOOGLE_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: staging-secrets
          key: oauth-google-client-secret
    - name: OAUTH_GITHUB_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: staging-secrets
          key: oauth-github-client-id
    - name: OAUTH_GITHUB_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: staging-secrets
          key: oauth-github-client-secret
    - name: ENVIRONMENT
      value: "staging"
    - name: LOG_LEVEL
      value: "INFO"
    - name: DEBUG
      value: "false"

web:
  replicaCount: 3
  image:
    repository: ai-market-web
    tag: "0.9.0-beta"
    pullPolicy: IfNotPresent
  
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  
  env:
    - name: REACT_APP_API_URL
      value: "https://api.staging.aimarketterminal.com"
    - name: REACT_APP_POSTHOG_KEY
      valueFrom:
        secretKeyRef:
          name: staging-secrets
          key: posthog-api-key

postgres:
  enabled: true
  image:
    repository: postgres
    tag: "15-alpine"
  
  auth:
    postgresPassword: "staging_secure_password_2024"
    database: "ai_market_terminal"
    username: "ai_market_user"
  
  primary:
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "standard"
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

redis:
  enabled: true
  image:
    repository: redis
    tag: "7-alpine"
  
  auth:
    enabled: false
  
  master:
    persistence:
      enabled: true
      size: 5Gi
      storageClass: "standard"
  
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/hsts: "true"
    nginx.ingress.kubernetes.io/hsts-max-age: "31536000"
    nginx.ingress.kubernetes.io/hsts-include-subdomains: "true"
  
  hosts:
    - host: staging.aimarketterminal.com
      paths:
        - path: /
          pathType: Prefix
          service:
            name: web-service
            port: 80
    - host: api.staging.aimarketterminal.com
      paths:
        - path: /
          pathType: Prefix
          service:
            name: api-service
            port: 8000
  
  tls:
    - secretName: staging-tls
      hosts:
        - staging.aimarketterminal.com
        - api.staging.aimarketterminal.com

monitoring:
  prometheus:
    enabled: true
    retention: "200h"
  
  grafana:
    enabled: true
    adminPassword: "staging_admin_2024"
    persistence:
      enabled: true
      size: 5Gi

secrets:
  enabled: true
  existingSecret: "staging-secrets"

config:
  enabled: true
  existingConfigMap: "staging-config"
